### ISSUE TITLE
best_model.pt usage 

### ISSUE THREAD

**Issue by nemeziz69** [Chris-hughes10/Yolov7-training#11]
How to properly load the best_model.pt model to run prediction on image?

**Comment by Chris-hughes10** [comment]
Hi, you can do this in two ways:
- using the Trainer, as described [here](https://pytorch-accelerated.readthedocs.io/en/latest/trainer.html#pytorch_accelerated.trainer.Trainer.load_checkpoint)
- creating the model using `model = create_yolov7_model(..., pretrained=False)` then loading the state dict from the checkpoint using `checkpoint = torch.load('best_model.pt', map_location="cpu"); model.load_state_dict(checkpoint["model_state_dict"])`

I hope this helps!
