### ISSUE TITLE
Request for yolov7-tiny weights

### ISSUE THREAD

**Issue by varshanth** [Chris-hughes10/Yolov7-training#12]
Hi, I do not see the release file for yolov7-tiny. Just wanted to know if you plan to release it? It is available from the official repo from here: https://github.com/WongKinYiu/yolov7/releases/download/v0.1/yolov7-tiny.pt

When I tried to load this ckpt myself, I encountered the following error:

```
(Pdb) torch.load('yolov7-tiny.pt', map_location="cpu")
*** AttributeError: Can't get attribute 'Model' on <module 'models.yolo' (namespace)>
```

Is there something special to be done to convert the official weights to the ones compatible with your repo?

Thanks in advance!

**Comment by Daraan** [comment]
While it would be amazing I think they do not provide the weights. There are two kinds provided: the [model].pt weights and the [model]-training.pt weights.
What we are using and want are the training weights for transfer learning.
The other weights are for prediction 

See also here: https://github.com/WongKinYiu/yolov7/issues/648

---

Btw. you can load these training weights if you clone the original yolov7 github, add your folder to sys.path then torch.load works.
Looking at the loaded model (while I'm not 100% sure) looks differently structured.

**Comment by Chris-hughes10** [comment]
Hi,

Hopefully I can provide some clarity on this.

The original repo provides serialised versions of the whole model. These are large and sensitive to the code and file structure of the codebase where they are used. For these reasons, PyTorch [recommends](https://pytorch.org/tutorials/beginner/saving_loading_models.html#save-load-state-dict-recommended) that state dicts are used instead; which offer much more flexibility.

When we were creating this repo, we ran the script located [here](https://github.com/Chris-hughes10/Yolov7-training/blob/main/extract_state_dicts.py) in the root of the original repo to extract the state dicts from their saved checkpoints (the `*-training` versions) and attached those to a release; which is used by our models. Therefore, our models use exactly the same weights, even though our implementations have been restructured slightly (for clarity and interpretability).


At the time, I believe that the weights for the tiny version was not available, which is why these were not included. It should be relatively simple to repeat this process to add the tiny weights. Unfortunately, I don't have much bandwidth to do this at the moment, but would welcome a PR and happy to advise if you would be willing to contribute this!

**Comment by varshanth** [comment]
> While it would be amazing I think they do not provide the weights. There are two kinds provided: the [model].pt weights and the [model]-training.pt weights. What we are using and want are the training weights for transfer learning. The other weights are for prediction
> 
> See also here: [WongKinYiu/yolov7#648](https://github.com/WongKinYiu/yolov7/issues/648)
> 
> Btw. you can load these training weights if you clone the original yolov7 github, add your folder to sys.path then torch.load works. Looking at the loaded model (while I'm not 100% sure) looks differently structured.

Hey, thanks for your reply. Yes, I have loaded and observed the weights. It's fine. For the YOLOv7 models which don't have RepConv, the only difference between the training and inference versions is that the implicit add and multiply modules are merged with the last Conv weights and biases. Theoretically, the inference versions can still be trained with the training code since Conv weights and bias are present in both versions. Mathematically, during training (by loading the inference version weights), the implicit modules will be randomly init'd and would/should learn to do the inverse operation (implicit multiply will learn implicit divide and implicit add will learn implicit subtract) to achieve convergence. Optionally, you can remove the implicit modules during training so that both the versions match and you wouldn't experience a significant performance drop. I have done both of these and confirm that both work.

**Comment by varshanth** [comment]
> Hi,
> 
> Hopefully I can provide some clarity on this.
> 
> The original repo provides serialised versions of the whole model. These are large and sensitive to the code and file structure of the codebase where they are used. For these reasons, PyTorch [recommends](https://pytorch.org/tutorials/beginner/saving_loading_models.html#save-load-state-dict-recommended) that state dicts are used instead; which offer much more flexibility.
> 
> When we were creating this repo, we ran the script located [here](https://github.com/Chris-hughes10/Yolov7-training/blob/main/extract_state_dicts.py) in the root of the original repo to extract the state dicts from their saved checkpoints (the `*-training` versions) and attached those to a release; which is used by our models. Therefore, our models use exactly the same weights, even though our implementations have been restructured slightly (for clarity and interpretability).
> 
> At the time, I believe that the weights for the tiny version was not available, which is why these were not included. It should be relatively simple to repeat this process to add the tiny weights. Unfortunately, I don't have much bandwidth to do this at the moment, but would welcome a PR and happy to advise if you would be willing to contribute this!

Hi, thanks for your explanation. The process was very quick and simple. I can confirm that the yolov7-tiny weights from the original repo are compatible with your repo and work fine for fine-tuning and also transfer learning. Just a small caveat as mentioned above, the provided weights were meant for inference, and so they have the implicit operations encoded in the last conv, i.e., they aren't available as explicit modules. Please note my above comment for alternate usages for fine-tuning/transfer-learning. As I am working on a delivery as well, I have some limited bandwidth, but I will send over a PR soon for the weights. Thanks!

**Comment by tkupek** [comment]
Awesome. Thanks a lot.
I have created a quick PR https://github.com/Chris-hughes10/Yolov7-training/pull/14, but the weights have to be added to the release and I can't to that without access to the repo.
@Chris-hughes10 would you mind uploading the file to releases?

**Comment by tkupek** [comment]
@varshanth before we merge, could you please double check if the state dict you uploaded is correct?
In comparison to the default `yolov7` weights I'm gettting pretty much garbage detections with the `tiny` version.

```
import numpy as np
import torch
from PIL import Image
from yolov7 import create_yolov7_model
from yolov7.plotting import show_image
from yolov7.trainer import filter_eval_predictions

model = create_yolov7_model(architecture="yolov7-tiny")
model.eval()

image = Image.open("test.jpg").convert("RGB")
image = np.array(image)
image = image / 255.
image = np.transpose(image, (2, 0, 1))
image = torch.tensor(image).float()
image = image.unsqueeze(dim=0)

outputs = model(image)
preds = model.postprocess(outputs)
preds = filter_eval_predictions(preds, confidence_threshold=0.35)

boxes = preds[0][:, :4]
class_ids = preds[0][:, -1]
show_image(image[0].permute(1, 2, 0), boxes.tolist(), class_ids.tolist())
```


![image](https://user-images.githubusercontent.com/4039384/233565354-0c1e0436-08e6-4c6c-b4b0-6f70dd6a9da0.png)
![image](https://user-images.githubusercontent.com/4039384/233565379-18aa4c26-c6d4-440b-9a85-2b448cc07c53.png)

**Comment by varshanth** [comment]
Hey @tkupek , as I mentioned in my comments [here](https://github.com/Chris-hughes10/Yolov7-training/issues/12#issuecomment-1468156363) and [here](https://github.com/Chris-hughes10/Yolov7-training/issues/12#issuecomment-1468167000), the **weights are for inference only**. What this means is that the implicit modules are merged with the last conv. If you wish to perform inference using the uploaded weights, then please remove/comment from [here](https://github.com/Chris-hughes10/Yolov7-training/blob/main/yolov7/models/core/detection_heads.py#L44) to [here](https://github.com/Chris-hughes10/Yolov7-training/blob/main/yolov7/models/core/detection_heads.py#L51), and replace the code [here](https://github.com/Chris-hughes10/Yolov7-training/blob/main/yolov7/models/core/detection_heads.py#L59)
```
x[layer_idx] = self.m[layer_idx](self.ia[layer_idx](x[layer_idx]))
x[layer_idx] = self.im[layer_idx](x[layer_idx])
```
to

```
x[layer_idx] = self.m[layer_idx](x[layer_idx])
```

This a junk output like this:
![test_pred_with_implicit_modules](https://user-images.githubusercontent.com/20283882/233687854-f1d65808-cbc0-4969-a692-c8319f9a7ce2.jpg)

becomes this:

![test_pred](https://user-images.githubusercontent.com/20283882/233687888-9ce6cabf-2283-4eb5-a47b-a146e363690a.jpg)

That being said, I want to re-iterate that if you wish to train:

1. Without the implicit modules, you can without a practically significant difference in performance.
2. With the implicit modules, you can still get a small boost, but you'll have to either
   a. Merge the implicit modules with the last conv yourself or
   b. Adjust with the presence of the implicit modules in your model.

Hope this helps!

**Comment by tkupek** [comment]
@varshanth thanks for the detailed description. Don't know why I missed the inference description but the adjusted code works!
