### ISSUE TITLE
Feature Request: Instance Segmentation

### ISSUE THREAD

**Issue by dariush-bahrami** [Chris-hughes10/Yolov7-training#6]
Hey Chris, First of all, I want to thank you for open-sourcing this implementation. Is there any chance of adding instance segmentation from the [original repo](https://github.com/WongKinYiu/yolov7#instance-segmentation-1)?

**Comment by Chris-hughes10** [comment]
Hi @dariush-bahrami, we currently do not have any plans to add this. It was a significant effort to migrate the detection codebase, and as the authors seem to have duplicated much of the codebase again to include segmentation, this looks like it would require a fair bit of time would be needed, which we currently do not have!

Apologies!
