### ISSUE TITLE
Run on GPU

### ISSUE THREAD

**Issue by nemeziz69** [Chris-hughes10/Yolov7-training#9]
How can I run the training with GPU?

**Comment by Chris-hughes10** [comment]
Hi, this repo uses [PyTorch-accelerated](https://github.com/Chris-hughes10/pytorch-accelerated) which handles training on the GPU. By default, just running the scripts using `python ...` will use 1 GPU if it is available.

For multiple GPUs, or setting mixed precision options, you can use the accelerate CLI commands to generate and use a config file, as described [here](https://pytorch-accelerated.readthedocs.io/en/latest/quickstart.html).
